server:
  port: 8088
spring:
  thymeleaf: # THYMELEAF
    encoding: UTF-8 #字符编码
    cache: false # 热部署静态文件
    mode: HTML5 # 使用HTML5标准
#  datasource: #数据源配置
#    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8 #数据库URL
#    username: test #用户名
#    password: 123456 #密码
#    driver-class-name: com.mysql.cj.jdbc.Driver #数据库驱动类
#  jpa: #配置jpa
#    show-sql: true #控制台是否显示sql
#    hibernate:
#      ddl-auto: none #应用启动时自动创建删除数据库
#    database-platform: org.hibernate.dialect.MySQL55Dialect
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB